// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dstgo/maxwell/internal/app/api"
	auth2 "github.com/dstgo/maxwell/internal/app/api/auth"
	"github.com/dstgo/maxwell/internal/app/data/cache"
	"github.com/dstgo/maxwell/internal/app/data/mq"
	"github.com/dstgo/maxwell/internal/app/data/repo"
	"github.com/dstgo/maxwell/internal/app/handler/auth"
	"github.com/dstgo/maxwell/internal/app/handler/email"
	"github.com/dstgo/maxwell/internal/app/types"
)

import (
	_ "github.com/ginx-contribs/ent-sqlite"
)

// Injectors from wire.go:

// initialize and setup app environment
func setup(env *types.Env) (api.Router, error) {
	routerGroup := env.Router
	appConf := env.AppConf
	jwtConf := appConf.Jwt
	client := env.Redis
	tokenHandler := auth.NewTokenHandler(jwtConf, client)
	entClient := env.Ent
	userRepo := repo.NewUserRepo(entClient)
	redisCodeCache := cache.NewRedisCodeCache(client)
	emailConf := appConf.Email
	mailClient := env.Email
	streamQueue := mq.NewStreamQueue(client)
	handler, err := email.NewEmailHandler(emailConf, mailClient, streamQueue)
	if err != nil {
		return api.Router{}, err
	}
	verifyCodeHandler := auth.NewVerifyCodeHandler(redisCodeCache, handler)
	authHandler := auth.NewAuthHandler(userRepo, tokenHandler, verifyCodeHandler)
	authAPI := auth2.NewAuthAPI(tokenHandler, authHandler, verifyCodeHandler)
	router := auth2.NewRouter(routerGroup, authAPI)
	apiRouter := api.Router{
		Auth: router,
	}
	return apiRouter, nil
}
