// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dstgo/maxwell/ent/container"
	"github.com/dstgo/maxwell/ent/job"
	"github.com/dstgo/maxwell/ent/mount"
	"github.com/dstgo/maxwell/ent/node"
	"github.com/dstgo/maxwell/ent/port"
	"github.com/dstgo/maxwell/ent/predicate"
	"github.com/dstgo/maxwell/ent/user"
)

// ContainerQuery is the builder for querying Container entities.
type ContainerQuery struct {
	config
	ctx        *QueryContext
	order      []container.OrderOption
	inters     []Interceptor
	predicates []predicate.Container
	withOwner  *UserQuery
	withNode   *NodeQuery
	withMounts *MountQuery
	withPorts  *PortQuery
	withJobs   *JobQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ContainerQuery builder.
func (cq *ContainerQuery) Where(ps ...predicate.Container) *ContainerQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *ContainerQuery) Limit(limit int) *ContainerQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *ContainerQuery) Offset(offset int) *ContainerQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *ContainerQuery) Unique(unique bool) *ContainerQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *ContainerQuery) Order(o ...container.OrderOption) *ContainerQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryOwner chains the current query on the "owner" edge.
func (cq *ContainerQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(container.Table, container.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, container.OwnerTable, container.OwnerPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNode chains the current query on the "node" edge.
func (cq *ContainerQuery) QueryNode() *NodeQuery {
	query := (&NodeClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(container.Table, container.FieldID, selector),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, container.NodeTable, container.NodePrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMounts chains the current query on the "mounts" edge.
func (cq *ContainerQuery) QueryMounts() *MountQuery {
	query := (&MountClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(container.Table, container.FieldID, selector),
			sqlgraph.To(mount.Table, mount.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, container.MountsTable, container.MountsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPorts chains the current query on the "ports" edge.
func (cq *ContainerQuery) QueryPorts() *PortQuery {
	query := (&PortClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(container.Table, container.FieldID, selector),
			sqlgraph.To(port.Table, port.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, container.PortsTable, container.PortsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJobs chains the current query on the "jobs" edge.
func (cq *ContainerQuery) QueryJobs() *JobQuery {
	query := (&JobClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(container.Table, container.FieldID, selector),
			sqlgraph.To(job.Table, job.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, container.JobsTable, container.JobsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Container entity from the query.
// Returns a *NotFoundError when no Container was found.
func (cq *ContainerQuery) First(ctx context.Context) (*Container, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{container.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *ContainerQuery) FirstX(ctx context.Context) *Container {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Container ID from the query.
// Returns a *NotFoundError when no Container ID was found.
func (cq *ContainerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{container.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *ContainerQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Container entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Container entity is found.
// Returns a *NotFoundError when no Container entities are found.
func (cq *ContainerQuery) Only(ctx context.Context) (*Container, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{container.Label}
	default:
		return nil, &NotSingularError{container.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *ContainerQuery) OnlyX(ctx context.Context) *Container {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Container ID in the query.
// Returns a *NotSingularError when more than one Container ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *ContainerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{container.Label}
	default:
		err = &NotSingularError{container.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *ContainerQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Containers.
func (cq *ContainerQuery) All(ctx context.Context) ([]*Container, error) {
	ctx = setContextOp(ctx, cq.ctx, "All")
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Container, *ContainerQuery]()
	return withInterceptors[[]*Container](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *ContainerQuery) AllX(ctx context.Context) []*Container {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Container IDs.
func (cq *ContainerQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, "IDs")
	if err = cq.Select(container.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *ContainerQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *ContainerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, "Count")
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*ContainerQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *ContainerQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *ContainerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, "Exist")
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *ContainerQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ContainerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *ContainerQuery) Clone() *ContainerQuery {
	if cq == nil {
		return nil
	}
	return &ContainerQuery{
		config:     cq.config,
		ctx:        cq.ctx.Clone(),
		order:      append([]container.OrderOption{}, cq.order...),
		inters:     append([]Interceptor{}, cq.inters...),
		predicates: append([]predicate.Container{}, cq.predicates...),
		withOwner:  cq.withOwner.Clone(),
		withNode:   cq.withNode.Clone(),
		withMounts: cq.withMounts.Clone(),
		withPorts:  cq.withPorts.Clone(),
		withJobs:   cq.withJobs.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ContainerQuery) WithOwner(opts ...func(*UserQuery)) *ContainerQuery {
	query := (&UserClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withOwner = query
	return cq
}

// WithNode tells the query-builder to eager-load the nodes that are connected to
// the "node" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ContainerQuery) WithNode(opts ...func(*NodeQuery)) *ContainerQuery {
	query := (&NodeClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withNode = query
	return cq
}

// WithMounts tells the query-builder to eager-load the nodes that are connected to
// the "mounts" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ContainerQuery) WithMounts(opts ...func(*MountQuery)) *ContainerQuery {
	query := (&MountClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withMounts = query
	return cq
}

// WithPorts tells the query-builder to eager-load the nodes that are connected to
// the "ports" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ContainerQuery) WithPorts(opts ...func(*PortQuery)) *ContainerQuery {
	query := (&PortClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withPorts = query
	return cq
}

// WithJobs tells the query-builder to eager-load the nodes that are connected to
// the "jobs" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ContainerQuery) WithJobs(opts ...func(*JobQuery)) *ContainerQuery {
	query := (&JobClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withJobs = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Container.Query().
//		GroupBy(container.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *ContainerQuery) GroupBy(field string, fields ...string) *ContainerGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ContainerGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = container.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Container.Query().
//		Select(container.FieldName).
//		Scan(ctx, &v)
func (cq *ContainerQuery) Select(fields ...string) *ContainerSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &ContainerSelect{ContainerQuery: cq}
	sbuild.label = container.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ContainerSelect configured with the given aggregations.
func (cq *ContainerQuery) Aggregate(fns ...AggregateFunc) *ContainerSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *ContainerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !container.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *ContainerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Container, error) {
	var (
		nodes       = []*Container{}
		_spec       = cq.querySpec()
		loadedTypes = [5]bool{
			cq.withOwner != nil,
			cq.withNode != nil,
			cq.withMounts != nil,
			cq.withPorts != nil,
			cq.withJobs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Container).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Container{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withOwner; query != nil {
		if err := cq.loadOwner(ctx, query, nodes,
			func(n *Container) { n.Edges.Owner = []*User{} },
			func(n *Container, e *User) { n.Edges.Owner = append(n.Edges.Owner, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withNode; query != nil {
		if err := cq.loadNode(ctx, query, nodes,
			func(n *Container) { n.Edges.Node = []*Node{} },
			func(n *Container, e *Node) { n.Edges.Node = append(n.Edges.Node, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withMounts; query != nil {
		if err := cq.loadMounts(ctx, query, nodes,
			func(n *Container) { n.Edges.Mounts = []*Mount{} },
			func(n *Container, e *Mount) { n.Edges.Mounts = append(n.Edges.Mounts, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withPorts; query != nil {
		if err := cq.loadPorts(ctx, query, nodes,
			func(n *Container) { n.Edges.Ports = []*Port{} },
			func(n *Container, e *Port) { n.Edges.Ports = append(n.Edges.Ports, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withJobs; query != nil {
		if err := cq.loadJobs(ctx, query, nodes,
			func(n *Container) { n.Edges.Jobs = []*Job{} },
			func(n *Container, e *Job) { n.Edges.Jobs = append(n.Edges.Jobs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *ContainerQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*Container, init func(*Container), assign func(*Container, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Container)
	nids := make(map[int]map[*Container]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(container.OwnerTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(container.OwnerPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(container.OwnerPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(container.OwnerPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Container]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "owner" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (cq *ContainerQuery) loadNode(ctx context.Context, query *NodeQuery, nodes []*Container, init func(*Container), assign func(*Container, *Node)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Container)
	nids := make(map[int]map[*Container]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(container.NodeTable)
		s.Join(joinT).On(s.C(node.FieldID), joinT.C(container.NodePrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(container.NodePrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(container.NodePrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Container]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Node](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "node" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (cq *ContainerQuery) loadMounts(ctx context.Context, query *MountQuery, nodes []*Container, init func(*Container), assign func(*Container, *Mount)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Container)
	nids := make(map[int]map[*Container]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(container.MountsTable)
		s.Join(joinT).On(s.C(mount.FieldID), joinT.C(container.MountsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(container.MountsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(container.MountsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Container]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Mount](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "mounts" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (cq *ContainerQuery) loadPorts(ctx context.Context, query *PortQuery, nodes []*Container, init func(*Container), assign func(*Container, *Port)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Container)
	nids := make(map[int]map[*Container]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(container.PortsTable)
		s.Join(joinT).On(s.C(port.FieldID), joinT.C(container.PortsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(container.PortsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(container.PortsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Container]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Port](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "ports" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (cq *ContainerQuery) loadJobs(ctx context.Context, query *JobQuery, nodes []*Container, init func(*Container), assign func(*Container, *Job)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Container)
	nids := make(map[int]map[*Container]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(container.JobsTable)
		s.Join(joinT).On(s.C(job.FieldID), joinT.C(container.JobsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(container.JobsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(container.JobsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Container]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Job](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "jobs" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (cq *ContainerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *ContainerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(container.Table, container.Columns, sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, container.FieldID)
		for i := range fields {
			if fields[i] != container.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *ContainerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(container.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = container.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ContainerGroupBy is the group-by builder for Container entities.
type ContainerGroupBy struct {
	selector
	build *ContainerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *ContainerGroupBy) Aggregate(fns ...AggregateFunc) *ContainerGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *ContainerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, "GroupBy")
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContainerQuery, *ContainerGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *ContainerGroupBy) sqlScan(ctx context.Context, root *ContainerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ContainerSelect is the builder for selecting fields of Container entities.
type ContainerSelect struct {
	*ContainerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *ContainerSelect) Aggregate(fns ...AggregateFunc) *ContainerSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *ContainerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, "Select")
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContainerQuery, *ContainerSelect](ctx, cs.ContainerQuery, cs, cs.inters, v)
}

func (cs *ContainerSelect) sqlScan(ctx context.Context, root *ContainerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
