// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/dstgo/maxwell/ent/container"
	"github.com/dstgo/maxwell/ent/job"
	"github.com/dstgo/maxwell/ent/mount"
	"github.com/dstgo/maxwell/ent/node"
	"github.com/dstgo/maxwell/ent/port"
	"github.com/dstgo/maxwell/ent/schema"
	"github.com/dstgo/maxwell/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	containerFields := schema.Container{}.Fields()
	_ = containerFields
	// containerDescCreatedAt is the schema descriptor for created_at field.
	containerDescCreatedAt := containerFields[5].Descriptor()
	// container.DefaultCreatedAt holds the default value on creation for the created_at field.
	container.DefaultCreatedAt = containerDescCreatedAt.Default.(func() int64)
	// containerDescUpdatedAt is the schema descriptor for updated_at field.
	containerDescUpdatedAt := containerFields[6].Descriptor()
	// container.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	container.DefaultUpdatedAt = containerDescUpdatedAt.Default.(func() int64)
	// container.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	container.UpdateDefaultUpdatedAt = containerDescUpdatedAt.UpdateDefault.(func() int64)
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescCreatedAt is the schema descriptor for created_at field.
	jobDescCreatedAt := jobFields[3].Descriptor()
	// job.DefaultCreatedAt holds the default value on creation for the created_at field.
	job.DefaultCreatedAt = jobDescCreatedAt.Default.(func() int64)
	// jobDescUpdatedAt is the schema descriptor for updated_at field.
	jobDescUpdatedAt := jobFields[4].Descriptor()
	// job.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	job.DefaultUpdatedAt = jobDescUpdatedAt.Default.(func() int64)
	// job.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	job.UpdateDefaultUpdatedAt = jobDescUpdatedAt.UpdateDefault.(func() int64)
	mountFields := schema.Mount{}.Fields()
	_ = mountFields
	// mountDescCreatedAt is the schema descriptor for created_at field.
	mountDescCreatedAt := mountFields[3].Descriptor()
	// mount.DefaultCreatedAt holds the default value on creation for the created_at field.
	mount.DefaultCreatedAt = mountDescCreatedAt.Default.(func() int64)
	// mountDescUpdatedAt is the schema descriptor for updated_at field.
	mountDescUpdatedAt := mountFields[4].Descriptor()
	// mount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mount.DefaultUpdatedAt = mountDescUpdatedAt.Default.(func() int64)
	// mount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mount.UpdateDefaultUpdatedAt = mountDescUpdatedAt.UpdateDefault.(func() int64)
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescUID is the schema descriptor for uid field.
	nodeDescUID := nodeFields[0].Descriptor()
	// node.DefaultUID holds the default value on creation for the uid field.
	node.DefaultUID = nodeDescUID.Default.(func() string)
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeFields[4].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() int64)
	// nodeDescUpdatedAt is the schema descriptor for updated_at field.
	nodeDescUpdatedAt := nodeFields[5].Descriptor()
	// node.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	node.DefaultUpdatedAt = nodeDescUpdatedAt.Default.(func() int64)
	// node.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	node.UpdateDefaultUpdatedAt = nodeDescUpdatedAt.UpdateDefault.(func() int64)
	portFields := schema.Port{}.Fields()
	_ = portFields
	// portDescCreatedAt is the schema descriptor for created_at field.
	portDescCreatedAt := portFields[3].Descriptor()
	// port.DefaultCreatedAt holds the default value on creation for the created_at field.
	port.DefaultCreatedAt = portDescCreatedAt.Default.(func() int64)
	// portDescUpdatedAt is the schema descriptor for updated_at field.
	portDescUpdatedAt := portFields[4].Descriptor()
	// port.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	port.DefaultUpdatedAt = portDescUpdatedAt.Default.(func() int64)
	// port.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	port.UpdateDefaultUpdatedAt = portDescUpdatedAt.UpdateDefault.(func() int64)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUID is the schema descriptor for uid field.
	userDescUID := userFields[0].Descriptor()
	// user.DefaultUID holds the default value on creation for the uid field.
	user.DefaultUID = userDescUID.Default.(func() string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() int64)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() int64)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() int64)
}
