// Code generated by ent, DO NOT EDIT.

package mount

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/dstgo/maxwell/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Mount {
	return predicate.Mount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Mount {
	return predicate.Mount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Mount {
	return predicate.Mount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Mount {
	return predicate.Mount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Mount {
	return predicate.Mount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Mount {
	return predicate.Mount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Mount {
	return predicate.Mount(sql.FieldLTE(FieldID, id))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldHost, v))
}

// Bind applies equality check predicate on the "bind" field. It's identical to BindEQ.
func Bind(v string) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldBind, v))
}

// IsDir applies equality check predicate on the "is_dir" field. It's identical to IsDirEQ.
func IsDir(v bool) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldIsDir, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldUpdatedAt, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.Mount {
	return predicate.Mount(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.Mount {
	return predicate.Mount(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.Mount {
	return predicate.Mount(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.Mount {
	return predicate.Mount(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.Mount {
	return predicate.Mount(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.Mount {
	return predicate.Mount(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.Mount {
	return predicate.Mount(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.Mount {
	return predicate.Mount(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.Mount {
	return predicate.Mount(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.Mount {
	return predicate.Mount(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.Mount {
	return predicate.Mount(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.Mount {
	return predicate.Mount(sql.FieldContainsFold(FieldHost, v))
}

// BindEQ applies the EQ predicate on the "bind" field.
func BindEQ(v string) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldBind, v))
}

// BindNEQ applies the NEQ predicate on the "bind" field.
func BindNEQ(v string) predicate.Mount {
	return predicate.Mount(sql.FieldNEQ(FieldBind, v))
}

// BindIn applies the In predicate on the "bind" field.
func BindIn(vs ...string) predicate.Mount {
	return predicate.Mount(sql.FieldIn(FieldBind, vs...))
}

// BindNotIn applies the NotIn predicate on the "bind" field.
func BindNotIn(vs ...string) predicate.Mount {
	return predicate.Mount(sql.FieldNotIn(FieldBind, vs...))
}

// BindGT applies the GT predicate on the "bind" field.
func BindGT(v string) predicate.Mount {
	return predicate.Mount(sql.FieldGT(FieldBind, v))
}

// BindGTE applies the GTE predicate on the "bind" field.
func BindGTE(v string) predicate.Mount {
	return predicate.Mount(sql.FieldGTE(FieldBind, v))
}

// BindLT applies the LT predicate on the "bind" field.
func BindLT(v string) predicate.Mount {
	return predicate.Mount(sql.FieldLT(FieldBind, v))
}

// BindLTE applies the LTE predicate on the "bind" field.
func BindLTE(v string) predicate.Mount {
	return predicate.Mount(sql.FieldLTE(FieldBind, v))
}

// BindContains applies the Contains predicate on the "bind" field.
func BindContains(v string) predicate.Mount {
	return predicate.Mount(sql.FieldContains(FieldBind, v))
}

// BindHasPrefix applies the HasPrefix predicate on the "bind" field.
func BindHasPrefix(v string) predicate.Mount {
	return predicate.Mount(sql.FieldHasPrefix(FieldBind, v))
}

// BindHasSuffix applies the HasSuffix predicate on the "bind" field.
func BindHasSuffix(v string) predicate.Mount {
	return predicate.Mount(sql.FieldHasSuffix(FieldBind, v))
}

// BindEqualFold applies the EqualFold predicate on the "bind" field.
func BindEqualFold(v string) predicate.Mount {
	return predicate.Mount(sql.FieldEqualFold(FieldBind, v))
}

// BindContainsFold applies the ContainsFold predicate on the "bind" field.
func BindContainsFold(v string) predicate.Mount {
	return predicate.Mount(sql.FieldContainsFold(FieldBind, v))
}

// IsDirEQ applies the EQ predicate on the "is_dir" field.
func IsDirEQ(v bool) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldIsDir, v))
}

// IsDirNEQ applies the NEQ predicate on the "is_dir" field.
func IsDirNEQ(v bool) predicate.Mount {
	return predicate.Mount(sql.FieldNEQ(FieldIsDir, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.Mount {
	return predicate.Mount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.Mount {
	return predicate.Mount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.Mount {
	return predicate.Mount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.Mount {
	return predicate.Mount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.Mount {
	return predicate.Mount(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Mount {
	return predicate.Mount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, OwnerTable, OwnerPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Container) predicate.Mount {
	return predicate.Mount(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Mount) predicate.Mount {
	return predicate.Mount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Mount) predicate.Mount {
	return predicate.Mount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Mount) predicate.Mount {
	return predicate.Mount(sql.NotPredicates(p))
}
